---
abstract: 'split a list in to two parts by way of a grep like block'
author:
  - 'Ben Hengst <notbenh@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Bisect
requires:
  Test::More: 0
version: 0.001_1
